spring:
  flyway:
    enabled: true
    baseline-on-migrate: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgres://fsjblzmokqmrwq:6653a940e147f00a2f0e40aea4b28cd5ec082ee322700875ce80f763620be50e@ec2-54-77-40-202.eu-west-1.compute.amazonaws.com:5432/da3mrpq3uonlgr
    username: fsjblzmokqmrwq
    password: 6653a940e147f00a2f0e40aea4b28cd5ec082ee322700875ce80f763620be50e
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8189}

jwt:
  secret: axioma-app
  expiration: 604800
  header: Authorization

